#!/bin/bash
set -e

export OPSANI_ENVOY_PROXY_SERVICE_PORT=${OPSANI_ENVOY_PROXY_SERVICE_PORT:-80}
export OPSANI_ENVOY_PROXIED_CONTAINER_ADDR=${OPSANI_ENVOY_PROXIED_CONTAINER_ADDR:-127.0.0.1}
export OPSANI_ENVOY_PROXIED_CONTAINER_PORT=${OPSANI_ENVOY_PROXIED_CONTAINER_PORT:-8080}

# TLS Configuration
export OPSANI_ENVOY_PROXIED_CONTAINER_TLS_ENABLED=${OPSANI_ENVOY_PROXIED_CONTAINER_TLS_ENABLED:-false}
export OPSANI_ENVOY_PROXIED_CONTAINER_TLS_VALIDATION=${OPSANI_ENVOY_PROXIED_CONTAINER_TLS_VALIDATION:-false}
export OPSANI_ENVOY_PROXIED_CONTAINER_TLS_ALT_NAME=${OPSANI_ENVOY_PROXIED_CONTAINER_TLS_ALT_NAME:-false}

# SNI - Validate upstream hostname
export OPSANI_ENVOY_PROXIED_CONTAINER_SNI_ENABLED=${OPSANI_ENVOY_PROXIED_CONTAINER_SNI_ENABLED:-false}
export OPSANI_ENVOY_PROXIED_CONTAINER_SNI_HOSTNAME=${OPSANI_ENVOY_PROXIED_CONTAINER_SNI_HOSTNAME:-dev.opsani.com}

export OPSANI_ENVOY_METRICS_PORT=${OPSANI_ENVOY_METRICS_PORT:-9901}
export OPSANI_ENVOY_HTTP2_ENABLED=${OPSANI_ENVOY_HTTP2_ENABLED:-false}

if [ "$OPSANI_ENVOY_HTTP2_ENABLED" == "true" ]; then
    export OPSANI_ENVOY_HTTP2_PROTOCOL_OPTIONS="http2_protocol_options: {}"
else
    export OPSANI_ENVOY_HTTP2_PROTOCOL_OPTIONS=""
fi

echo "Generating envoy.yaml config file..."
cat /tmpl/envoy.yaml.tmpl | envsubst > /etc/envoy.yaml

echo "---"
cat /etc/envoy.yaml
echo "---\n"

echo "Starting Envoy..."
exec "$@"
